name: Build Recovery Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install repo git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
    
    - name: 克隆rec
      run: |
        git clone -b twrp-12.1 https://github.com/SOVIET-ANDROID/android_device_xiaomi_raphael-orangefox
  
    - name: 同步设备树
      run: |
           repo init -u https://android.googlesource.com/platform/manifest
           repo sync

    - name: 移动目录
      run: |
           mkdir -p device/xiaomi
           mv android_device_xiaomi_raphael-orangefox device/xiaomi/raphael
           
    - name: 初始化环境
      run: |
           source build/envsetup.sh

    - name: 构建rec
      run: |
           lunch twrp_raphael-eng && mka recoveryimage

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: recoveryimage
        path: out/target/product/raphael/recovery.img
