name: Build OrangeFox Recovery with EROFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        repository: SOVIET-ANDROID/android_device_xiaomi_raphael-orangefox

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        ndk: '21.3.6528147'
        cache-build-tools: true

    - name: Configure kernel for EROFS
      run: |
        # Assuming the kernel source code is already in the right directory
        cd kernel/xiaomi/raphael
        if [ ! -f .config ]; then make defconfig; fi
        echo "CONFIG_EROFS_FS=y" >> .config

    - name: Build OrangeFox Recovery
      run: |
        source build/envsetup.sh
        lunch twrp_raphael-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v2
      with:
        name: recovery.img
        path: out/target/product/raphael/recovery.img
