name: Build OrangeFox Recovery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Clone OrangeFox repository
      run: git clone https://github.com/SOVIET-ANDROID/android_device_xiaomi_raphael-orangefox android_device_xiaomi_raphael-orangefox

    - name: Update BoardConfig.mk for EROFS
      run: |
        sed -i 's/TARGET_USERIMAGES_USE_F2FS := true/TARGET_USERIMAGES_USE_F2FS := false/' android_device_xiaomi_raphael-orangefox/BoardConfig.mk

    - name: Lunch and build OrangeFox Recovery
      run: |
        cd android_device_xiaomi_raphael-orangefox
        source build/envsetup.sh
        lunch twrp_raphael-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v2
      with:
        name: recovery.img
        path: android_device_xiaomi_raphael-orangefox/out/target/product/raphael/recovery.img
