name: Build Recovery Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        
    - name: Setup repo command
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
      env:
        PATH: ~/bin:${{ github.workspace }}/bin:${{ env.PATH }}

    - name: Sync the repository
      run: |
        repo init -u https://github.com/SOVIET-ANDROID/android_device_xiaomi_raphael-orangefox -b twrp-12.1
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune

    - name: Set up environment
      run: |
        source build/envsetup.sh
        lunch twrp_raphael-eng

    - name: Build recovery image
      run: |
        mka recoveryimage

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: recoveryimage
        path: out/target/product/raphael/recovery.img
