name: Build Recovery Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: 安装 repo 工具
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

    - name: 初始化和同步 AOSP 代码库
      run: |
        mkdir -p ~/android/lineage
        cd ~/android/lineage
        repo init -u https://android.googlesource.com/platform/manifest
        repo sync -j$(nproc)

    - name: 克隆设备树
      run: |
        mkdir -p ~/android/lineage/device/xiaomi
        git clone -b twrp-12.1 https://github.com/SOVIET-ANDROID/android_device_xiaomi_raphael-orangefox ~/android/lineage/device/xiaomi/raphael

    - name: 设置环境变量
      run: |
        cd ~/android/lineage
        source build/envsetup.sh
      env:
        PATH: ~/bin:$PATH

    - name: 选择构建目标
      run: |
        cd ~/android/lineage
        lunch twrp_raphael-eng
      env:
        PATH: ~/bin:$PATH

    - name: 构建 Recovery 镜像
      run: |
        cd ~/android/lineage
        mka recoveryimage
      env:
        PATH: ~/bin:$PATH

    - name: 上传构建产物
      uses: actions/upload-artifact@v2
      with:
        name: recoveryimage
        path: ~/android/lineage/out/target/product/raphael/recovery.img
