name: Build Recovery Image

on:
  push:
    branches:
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: 安装控制
      run: |
        wget https://dl.todesk.com/linux/todesk-v4.7.2.0-amd64.deb
        sudo apt-get install ./todesk-v4.7.2.0-amd64.deb
        /opt/todesk/bin/ToDesk_Host -deploy xinxu.xin
        todesk
      
    - name: 安装依赖
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install repo git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
        
    - name: 安装repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
        chmod +x /usr/local/bin/repo
        repo --version
        


    
    - name: 初始化和同步 AOSP 代码库
      run: |
        mount | grep /mnt
        sudo mkdir -p /mnt/android/lineage
        cd /mnt/android/lineage
        sudo repo init -u https://android.googlesource.com/platform/manifest
        sudo repo sync -j$(nproc)
        

    - name: 克隆设备树
      run: |
        sudo mkdir -p /mnt/android/lineage/device/xiaomi
        sudo git clone -b twrp-12.1 https://github.com/SOVIET-ANDROID/android_device_xiaomi_raphael-orangefox ~/android/lineage/device/xiaomi/raphael

    - name: 设置环境变量
      run: |
        cd /mnt/android/lineage
        sudo source build/envsetup.sh

    - name: 选择构建目标
      run: |
        cd /mnt/android/lineage
        lunch twrp_raphael-eng

    - name: 构建 Recovery 镜像
      run: |
        cd /mnt/android/lineage
        mka recoveryimage

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: recoveryimage
        path: /mnt/android/lineage/out/target/product/raphael/recovery.img
